set_property DONT_TOUCH true [get_cells -hier *sbox0]
set_property DONT_TOUCH true [get_cells -hier *key0]
#set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets Base_Zynq_MPSoC_i/RO_1/inst/outclk]
set_power_opt -exclude_cells [get_cells my_module/my_bram1]
set_property PACKAGE_PIN AG14 [get_ports {led_4bits_tri_o[3]}]
set_property PACKAGE_PIN AF13 [get_ports {led_4bits_tri_o[2]}]
set_property PACKAGE_PIN AE13 [get_ports {led_4bits_tri_o[1]}]
set_property PACKAGE_PIN AJ14 [get_ports {led_4bits_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[0]}]
set_property PACKAGE_PIN AG15 [get_ports {push_button_4bits_tri_i[3]}]
set_property PACKAGE_PIN AE14 [get_ports {push_button_4bits_tri_i[2]}]
set_property PACKAGE_PIN AF15 [get_ports {push_button_4bits_tri_i[1]}]
set_property PACKAGE_PIN AE15 [get_ports {push_button_4bits_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_button_4bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_button_4bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_button_4bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_button_4bits_tri_i[0]}]
